FROM php:8.2-apache-bullseye

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    default-mysql-client \
    && docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www/html

# configure php and apache
RUN a2enmod rewrite
RUN pear install PHP_CodeSniffer
COPY docker/apache/httpd.conf /etc/apache2/sites-enabled/000-default.conf

# install composer
RUN curl -Ss https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy only necessary application files and folders
COPY composer.json composer.lock ./
COPY ./bin ./bin
COPY ./config ./config
COPY ./public/index.php ./public/index.php
COPY ./public/robots.txt ./public/robots.txt
COPY ./public/favicon.png ./public/favicon.png 
COPY ./src ./src
COPY ./templates ./templates
COPY ./translations ./translations
COPY ./migrations ./migrations
COPY ./var ./var
COPY ./.env ./.env
COPY ./.env.prod ./.env.prod
COPY --from=assets-builder /app/public/build ./public/build

ENV COMPOSER_ALLOW_SUPERUSER=1

# Install dependencies
RUN composer install --no-scripts


